version: "3.3"
services:
  couchdb_01:
    image: couchdb
    container_name: couchdb01
    environment:
      COUCHDB_USER: rob
      COUCHDB_PASSWORD: 123456
    ports:
      - "5984:5984"
    volumes:
      - ./dbdata:/opt/couchdb/data
