version: "3.3"
services:
  mysql_01:
    image: mysql/mysql-server
    container_name: mysql01
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
